### ISSUE TITLE
Forced EDNS Client Subnet

### ISSUE THREAD

**Issue by aer0nix** [DNSCrypt/encrypted-dns-server#73] opened 2021-08-15 12:35 UTC
Please add edns_client_subnet from dnscrypt-proxy to here for all upstream queries, because without it some CDN have much latency.

**Comment by jedisct1** [comment] 2021-08-15 16:55
Duplicate of #32

**Closed by jedisct1** 2021-08-15 16:55 UTC

**Comment by aer0nix** [comment] 2021-08-15 19:40
This is not duplicate. I talk about different feature.
